name: NuGet_Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    env:
      NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_TOKEN}}

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build FLAnimatedImage
      run: |
        cd src/Flipboard.FLAnimatedImage.Xamarin
        dotnet restore
        msbuild Flipboard.FLAnimatedImage.Xamarin.csproj /p:Configuration=Release
    - name: Publish Flipboard.FLAnimatedImage.Xamarin
      run: |
        cd nuget
        nuget pack Flipboard.FLAnimatedImage.Xamarin.nuspec
        nuget push "*.nupkg" -SkipDuplicate -NoSymbols -ApiKey $NUGET_AUTH_TOKEN -Source https://api.nuget.org/v3/index.json
